### ISSUE TITLE
Native Error running on node 6.3.1, Windows 8

### ISSUE THREAD

**Issue by metabench** [dominictarr/tacodb#10]
I get the following error when I run the getting started instructions on node 6.3.1, Windows 8

`tacodb local taco.js --port 8080`

```
C:\Users\me\AppData\Roaming\npm\node_modules\tacodb\node_modules\bindings\bindings.js:83
        throw e
        ^

Error: error: 193\\?\C:\Users\me\AppData\Roaming\npm\node_modules\tacodb\node_modules\leveldown\build\Release\leveldown.node
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at bindings (C:\Users\me\AppData\Roaming\npm\node_modules\tacodb\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\tacodb\node_modules\leveldown\index.js:1:99)
    at Module._compile (module.js:541:32)

```

**Comment by dominictarr** [comment]
ah, I'm not working on this anymore. I recommend just using level with level-sublevel.
